on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSE_RUNNER: "docker compose"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git config --global --add safe.directory /__w/quoteguide-functions/quoteguide-functions

      - name: Setup the application environment
        run: make install

      - name: Put everything up
        run: make up

      - name: Configure database environment
        run: make migrate

      - name: Run tests and generate coverage
        run: make test

      - name: Run SonarCloud analysis
        run: make sonar
