on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: devitools/hyperf:8.3-dev
      env:
        SCAN_CACHEABLE: false
        STDOUT_LOG_LEVEL: alert,critical,emergency,error,warning,notice,info
      options: --cpus 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: composer install

      - run: composer lint
