on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: "true"
          reactions: "rocket"
          summaryEnabled: "true"
