on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: devitools/hyperf:8.3-dev
      env:
        SCAN_CACHEABLE: false
        STDOUT_LOG_LEVEL: alert,critical,emergency,error,warning,notice,info
      options: --cpus 1

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git config --global --add safe.directory /__w/hyperf-com-rapadura/hyperf-com-rapadura

      - run: composer install

      - run: php bin/hyperf.php migrate --database=postgres

      - run: composer test

      - run: /bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
